------------------------------------------------------
-- Autor       : I.E.S Sotero Hernández
-- Descripción : Script Inserciones tabla "Cursa" - Formación SQL
------------------------------------------------------

--Inserciones para la tabla Cursa (Study)
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 1, 7.55);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 2, 8.2);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 3, 8.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 4 ,9.55);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 5, 7.25);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (1, 6, 6.75);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 1, 7.25);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 2, 4.87);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 3, 8.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 4, 9.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 5, 6.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (2, 6, 7.82);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 1, 6.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 2, 7.45);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 3, 8.45);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 4, 8.67);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 5, 6.25);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (3, 6, 6.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (4, 8, 5.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (4, 9, 6.25);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (4, 10, 8.25);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (4, 11, 9.35);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (4, 12, 6.78);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (5, 8, 7.8);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (5, 9, 7.55);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (5, 10, 8.75);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (5, 11, 10);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (5, 12, 7.45);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (6, 8, 8.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (6, 10, 8.3);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (6, 11, 8.67);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (6, 12, 7.45);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (7, 13, 6.3);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (7, 14, 7.2);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (7, 15, 8.76);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (7, 16, 5.6);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (7, 17, 7.79);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (8, 13, 8.56);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (8, 14, 10);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (8, 15, 8.44);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (8, 16, 6.87);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (8, 17, 7.6);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (9, 13, 8.89);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (9, 14, 7.43);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (9, 15, 8.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (9, 16, 7.4);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 18, 7.6);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 19, 7.7);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 20, 8.65);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 21, 9.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 22, 8.3);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (10, 23, 7.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (11, 18, 7.7);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (11, 19, 6.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (11, 21, 9.5);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (11, 22, 5.8);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (11, 23, 7.6);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (12, 18, 8.54);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (12, 19, 5.2);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (12, 21, 7.58);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (12, 22, 8.95);
INSERT INTO Study (cod_student,cod_module,mark)
VALUES (12, 23, 6.42);
